services:
  ad-meetingcalendar:
    build:
      context: .
    container_name: ad-meetingcalendar-service
    ports:
      - "8000:8000"
      
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
        - path: ./.env                     # ✅ Add this line
          target: /var/www/html/.env       # ✅ Ensures .env is available
          action: sync          
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: ad-meetingcalendar-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: CalendarDB
    ports:
      - "23567:27017"
    volumes:
      - ad-meetingcalendar-mongodb:/data/db

  postgresql:
    image: postgres:15
    container_name: ad-meetingcalendar-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendardb
    ports:
      - "5555:5432"
    volumes:
      - ad-meetingcalendar-postgresql:/data/db/postgresql

volumes:
  ad-meetingcalendar-mongodb:
    driver: local
  ad-meetingcalendar-postgresql:
    driver: local
